version: '2'

networks:
  web:
  data:

services:
  nginx:
    container_name: pay-demo-nginx-frontend
    image: nginx
    networks:
      - web
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./dist/:/var/www/html/:ro
    restart: always

  frontend:
    build: .
    ports:
      - "8000:5173"
    volumes:
      - .:/app/
