version: '2'

networks:
  web:
  data:

# nginx 設定中的 fastcgi_param 如果要生效，則程式碼在容器 nginx 和 php 放置的位置要相同
# 所以 volumes 都有一行一樣的 .:/var/www/html
# 參考 https://stackoverflow.com/questions/71475528/i-get-fastcgi-primary-script-unknown-error-in-a-nginx-php-fpm-containers-sit
services:
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - web
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - .:/var/www/html
    restart: always

  php:
    container_name: php
    image: webdevops/php:7.4-alpine
    networks:
      - web
      - data
    volumes:
      - .:/var/www/html
    restart: always
